### ISSUE TITLE
Blind scan

### ISSUE THREAD

**Issue by 3xtr3m3d** [zgemma-star/e2plugins#1]
Hi

Is there any possibility to add a blind scan plugin for Zgemma models?

Regards

**Comment by zgemma-star** [comment]
The hisilicon models like H9 model has blindscan

**Comment by 3xtr3m3d** [comment]
@zgemma-star  any plans for models like h52s? Looking at datasheets of tuners seems like they are capable of doing blindscans but no drivers for that though

**Comment by zgemma-star** [comment]
Support for blindscan is only on the H9
